<!-- JAVASCRIPT -->
{{-- <script src="{{ URL::asset('assets1/libs/jquery/jquery.min.js') }}"></script>
<script src="{{ URL::asset('assets1/libs/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ URL::asset('assets1/libs/metismenu/metisMenu.min.js') }}"></script>
<script src="{{ URL::asset('assets1/libs/simplebar/simplebar.min.js') }}"></script>
<script src="{{ URL::asset('assets1/libs/node-waves/waves.min.js') }}"></script>
<script src="{{ asset('assets1/libs/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets1/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets1/libs/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets1/libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets1/libs/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('assets1/libs/pdfmake/build/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets1/libs/pdfmake/build/vfs_fonts.js') }}"></script>
<script src="{{ asset('assets1/libs/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('assets1/libs/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('assets1/libs/datatables.net-buttons/js/buttons.colVis.min.js') }}"></script>
<script src="{{ asset('assets1/libs/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('assets1/libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ URL::asset('assets1/js/app.js') }}"></script> --}}


<script src="{{ asset('assets1/alert.js') }}"></script>
<script src="{{ asset('assets1/libs/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('assets1/libs/metismenu/metisMenu.min.js') }}"></script>
<script src="{{ asset('assets1/libs/simplebar/simplebar.min.js') }}"></script>
<script src="{{ asset('assets1/libs/node-waves/waves.min.js') }}"></script>
<script src="{{ asset('assets1/libs/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets1/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets1/libs/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets1/libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets1/libs/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('assets1/libs/pdfmake/build/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets1/libs/pdfmake/build/vfs_fonts.js') }}"></script>
<script src="{{ asset('assets1/libs/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('assets1/libs/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('assets1/libs/datatables.net-buttons/js/buttons.colVis.min.js') }}"></script>
<script src="{{ asset('assets1/libs/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('assets1/libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets1/js/pages/datatables.init.js') }}"></script>
<script src="{{ asset('assets1/js/app.js') }}"></script>
<script src="{{ asset('assets1/libs/parsleyjs/parsley.min.js') }}"></script>
<script src="{{ asset('assets1/js/pages/form-validation.init.js') }}"></script>
<script src="{{ asset('assets1/libs/select2/js/select2.min.js') }}"></script>
<script src="{{ asset('assets1/libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ asset('assets1/libs/spectrum-colorpicker2/spectrum.min.js') }}"></script>
<script src="{{ asset('assets1/libs/bootstrap-timepicker/js/bootstrap-timepicker.min.js') }}"></script>
<script src="{{ asset('assets1/libs/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js') }}"></script>
<script src="{{ asset('assets1/libs/bootstrap-maxlength/bootstrap-maxlength.min.js') }}"></script>
<script src="{{ asset('assets1/libs/@chenfengyuan/datepicker/datepicker.min.js') }}"></script>
<script src="{{ asset('assets1/js/pages/form-advanced.init.js') }}"></script>
<script src="{{ asset('assets1/libs/jquery-steps/build/jquery.steps.min.js') }}"></script>
<script src="{{ asset('assets1/numeral.js') }}"></script>
<script src="{{ asset('assets1/libs/inputmask/min/jquery.inputmask.bundle.min.js') }}"></script>
<script src="{{ asset('assets1/js/pages/form-mask.init.js') }}"></script>
